location_names: 
  - L0
  - L1
L0_point: {
  x: 0.2,
  y: 1.65,
  z: 0.0,
}
L1_point: {
  x: -0.2,
  y: 1.65,
  z: 0.0,
}
L2_point: {
  x: 0.4,
  y: -0.4,
  z: 0.1,
}
init_state: # State values: solid, drilled, collected
  - stow # ee location
  - not_holding # Specify whether the digger is holding a sample
  - solid
  - solid