object_ids:
  - pink_box_1
  - blue_box_1
  #- blue_box_2
  #- green_box_1

object_types:
  - "box"
  - "box"
  #- "box"
  #- "box"

blue_box_1: {
  l: 0.064,
  w: 0.044,
  h: 0.16,
}

blue_box_2: {
  l: 0.064,
  w: 0.044,
  h: 0.16,
}

pink_box_1: {
  l: 0.064,
  w: 0.044,
  h: 0.16,
}

green_box_1: {
  l: 0.064,
  w: 0.044,
  h: 0.16,
}

object_orientation_types:
  - up_y
  - up_y
  #- up_y
  #- up_y

initial_locations: {
  pink_box_1: "L3",
  blue_box_1: "L1",
  #blue_box_2: "L2",
  #green_box_1: "L4",
}